name: pixelsweb
favicon: null
layout_spectrum: 0.8591209566220641
typography_spectrum: 0.11686712014488876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.1875
  lightness: 0.3887216877192259
  saturation: 0.6754257983993739
  rhythmicContrast: 0.8401012378744781
purpose: []
